activitytracker/Models/ActivityModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace activitytracker.Models
{
    public class ActivityModel
    {
        [Required]
        public string Activity { get; set; }

        [Required]
        public string Location { get; set; }
    }
}

activitytracker/Models/ErrorViewModel.cs
using System;

namespace activitytracker.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

activitytracker/Models/TestModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace activitytracker.Models
{
    public class TestModel
    {
        [Required]
        public string Email { get; set; }
    }
}

activitytracker/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace activitytracker.Controllers
{
    public class ActivityController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            return View();
        }

        // GET: Test/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Test/Create
        public ActionResult Create()
        {
            // new code starts here
            // need to ask Mike
            /*
            var sqlTest = new SQLTest();
            sqlTest.testDatabase();
            */
            // new code ends here
            return View();
        }

        // POST: Test/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string activity, string location)
        {
            try
            {
                var sqlTest = new SQLTest();
                sqlTest.saveData(activity, location);

                return RedirectToAction("Profile", "Home");
                
            }
            catch
            {
                return RedirectToAction("Activities", "Home");
            }
        }

        // GET: Test/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Test/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Test/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Test/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

activitytracker/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using activitytracker.Models;

namespace activitytracker.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Profile()
        {
            ViewData["Greeting"] = "Welcome User! This will be your profile page!";

            var sqlTest = new SQLTest();
            var testDataTable = sqlTest.testDatabase();
            ViewData["Database!"] = testDataTable;
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Activities()
        {
            ViewData["Message"] = "Enter new activies and locations here";

            return View();
        }

        public IActionResult Maps()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

activitytracker/Controllers/TrackerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace activitytracker.Controllers
{
    [Produces("application/json")]
    [Route("api/Tracker")]
    public class TrackerController : Controller
    {
        // GET: api/Tracker
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET: api/Tracker/5
        [HttpGet("{id}", Name = "Get")]
        public int Get(int id)
        {
            return id;
        }

        // POST: api/Tracker
        [HttpPost]
        public object Post(PostData data)
        {
            //TODO: Save some stuff to a database
            var sqlTest = new SQLTest();
            sqlTest.saveTimeTracker(data.ActivityType, data.ActivityName, data.CurrentTime, data.TotalTime);
            return new { Success = true};
        }

        // PUT: api/Tracker/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/ApiWithActions/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }

    public class PostData
    {
        public string ActivityType { get; set; }
        public string ActivityName { get; set; }
        public int CurrentTime { get; set; }
        public int TotalTime { get; set; }
    }
}

activitytracker/Views/Home/Activities.cshtml
@{
    ViewData["Title"] = "Activities";
}

<h2>@ViewData["Message"]</h2>


@model activitytracker.Models.ActivityModel

@using (Html.BeginForm("Create", "Activity", FormMethod.Post))
{
    //new code starts here <!--

    @Html.DropDownListFor(x => x.Activity, new List<SelectListItem>
    {
        new SelectListItem() {Text = "Enter Activity", Value="defaultSelection"},
        new SelectListItem() {Text = "Biking (Road)", Value="roadBiking"},
        new SelectListItem() {Text = "Biking (Mountain)", Value="mountainBiking"},
        new SelectListItem() {Text = "Hiking", Value="hiking"},
        new SelectListItem() {Text = "Swimming", Value="swimming"},
        new SelectListItem() {Text = "Running", Value="running"},
        new SelectListItem() {Text = "Walking", Value="walking"},
        new SelectListItem() {Text = "Rock Climbing", Value="rockClimbing"},
        new SelectListItem() {Text = "Kayaking", Value="kayaking"}
    }) @:&nbsp;

    //new code ends here
    @Html.LabelFor(model => model.Activity)@:&nbsp;
    @Html.TextBoxFor(model => model.Activity, new { placeholder = "Enter Activity Here" })@:&nbsp;
    @Html.ValidationMessageFor(model => model.Activity)
    @Html.LabelFor(model => model.Location)@:&nbsp;
    @Html.TextBoxFor(model => model.Location, new { placeholder = "Enter Location Here" })@:&nbsp;
    @Html.ValidationMessageFor(model => model.Location)
    <button type="submit" class="btn btn-primary">Submit Data</button>
}

activitytracker/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

activitytracker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>
    <style>
        .carousel-inner > .item {
            height: 400px;
        }
    </style>
</head>

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/pinmap.jpg" alt="ASP.NET" class="img-responsive" /><
            <div class="carousel-caption" role="option">
                <p>
                    Track every vacation, every activity, and keep every memory.
                    <a class="btn btn-default" href="https://www.google.com">
                        Begin tracking now!
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/carmap.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Plan out the next favorite vacation, and find out what fun stuff there is to do.
                    <a class="btn btn-default" href="https://www.google.com">
                        Plan now!
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/biking.jpg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Save every moment so you can experience it forever.
                    <a class="btn btn-default" href="https://www.google.com">
                        Track now!
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/hiking.jpg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Whether you're an adrenaline junkie or a laid back relaxer, you can keep track of it all.
                    <a class="btn btn-default" href="https://www.google.com">
                        Save it!
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Vacation and Activity Tracker</h2>
        <ul>
            <li>Log Vacations</li>
            <li>Track your activity</li>
            <li>Get suggestions for new places to go and new things to do</li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Where do you want to go?</h2>
        <ul>
            <li>The Mountains?</li>
            <li>The Ocean?</li>
            <li>The Beach?</li>
            <li>The City?</li>
            <li>Another country?</li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>What do you want to do?</h2>
        <ul>
            <li>Mountain Biking</li>
            <li>Biking</li>
            <li>Hiking</li>
            <li>Rock Climbing</li>
            <li>Kayaking</li>
            <li>Camping</li>
            <li>Bird Watching</li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Go Anwhere - Do anything</h2>
        <ul>
            <li>Live your life</li>
            <li>Have fun</li>
            <li>Do amazing things</li>
        </ul>
    </div>
</div>

activitytracker/Views/Home/Maps.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Maps</title>
    <style>
        /* Always set the map height explicitly to define the size of the div
        * element that contains the map. */
        #map {
            height: 100%;
        }
        /* Optional: Makes the sample page fill the window. */
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
    </style>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">activitytracker</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Profile">Profile</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Activities">Activities</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Maps">Maps</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="map"></div>
    <script>
        var map;
        function initMap() {
            map = new google.maps.Map(document.getElementById('map'), {
                center: { lat: 44.789552, lng: -93.516498 },
                zoom: 8
            });
        }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBZMDZwhNVHvWIVcnnpFGVzzzxFLzJk8qg&callback=initMap"
            async defer></script>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

</body>
</html>

activitytracker/Views/Home/Profile.cshtml
@using System.Data;

<head>
    <style>
        #activity-table {
            border: 1px solid black;
            border-collapse: separate;
            border-spacing: 30px 15px;
        }

        #tableHeading {
            border-bottom: 3px solid black;
        }
    </style>
</head>

@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>
<h3>@ViewData["Greeting"]</h3>

@{
    DataTable dt = (DataTable)ViewData["Database!"];
}

<p>Use this area to provide additional information.</p>
<p>Here is a new change to test Github Connection.</p>

<table id="activity-table">
    <tr>
        <th id="tableHeading">Activity</th>
        <th id="tableHeading">Location</th>
    </tr>
    @foreach (DataRow row in dt.Rows)
    {
        <tr>
            <td>@row.ItemArray[0]</td>
            <td>@row.ItemArray[1]</td>
        </tr>
    }
</table>

activitytracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - activitytracker</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">activitytracker</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Profile">Profile</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Activities">Activities</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Maps">Maps</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Anthony Stender</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>